### ISSUE TITLE
Names are not properly parsing

### ISSUE THREAD

**Issue by jasonbronson** [ProfChaos/torrent-name-parser#1]
I tested this on a large number of names and noticed lots of the names are not working. 
[https://gist.github.com/jasonbronson/1d7957ce9a6683fe56268428a090b070](url)

**Comment by ProfChaos** [comment]
Do you have any examples of the ones that aren't working?

**Comment by jasonbronson** [comment]
You can download example here. 

[https://goplay.tools/snippet/3M1VmBlf6x_6](url)

Some examples are 

urder on the Orient Express 2017 BRRip x264 AAC-SSN
Dracula vs Frankentein 1971 720p BluRay x264 x0r
The Ballad of Lefty Brown 2017 1080p BluRay x264 DTS-HD MA 5 1-MT
Leap Year 2010 720p BluRay x264 x0r
The Ballad of Lefty Brown 2017 BluRay 1080p DTS-HD MA 5 1 AVC REMUX-FraMeSToR
Cast a Giant Shadow 1966 720p BluRay x264 x0r
Sophie and the Rising Sun 2016 720p BluRay x264-SADPANDA
I Am Not a Witch 2017 BluRay 1080p DTS-HD MA 5 1 AVC REMUX-FraMeSToR
The Silence of the Lambs 1991 Criterion Collection 1080p BluRay REMUX AVC DTS-HD MA 5 1-EPSiLON
[REQ] Shank 2010 BDRip XviD-AVCDVD
[REQ] Man About Dog 2004 DVDRiP XViD-BNU
Daddy's Home 2 2017 BluRay 1080p x264 Atmos TrueHD 7 1-HDC
The Florida Project 2017 BluRay 1080p DTS-HD MA 5 1-MT
Murder On The Orient Express 2017 720p BluRay x264 x0r
Scent of a Woman 1992 1080p BluRay REMUX VC-1 DTS-HD MA 5 1-EPSiLON
Mom and Dad 2017 720p BluRay x264 DTS-CHD
The High Cost of Loving 1958 DVDRip XViD
[Dual] The Harder They Fall 1956 MULTi 1080p BluRay x264-FiDELiO
The Boy Next Door 2015 720p BluRay x264 x0r
Kismet 1955 720p BluRay x264 x0r
Leap Year 2010 BluRay 1080p DTS-HD MA 5 1 AVC HYBRID REMUX-FraMeSToR
The Fog 1980 Collector's Edition BluRay 1080p DTS-HD MA 5 1 AVC REMUX-FraMeSToR
Ali 2001 Blu-ray 1080p AVC DTS-HD MA 5 1 REMUX-FraMeSToR
Fifty Shades Freed (2018) 700MB HDCAM x264 AAC - DerpusMaximus
Maze Runner The Death Cure 2018 CAM XViD AC3 ETRG
What We Do in The Shadows 2014 PLSUB 720p BluRay x264 INTERNAL-FLAME
What We Do in The Shadows 2014 PLSUB 1080p BluRay x264 INTERNAL-FLAME
Accident Man 2018 720p BRRip X264 AC3 MutzNutz
Gran Torino 2008 BRRIP 720p x264 AAC INFERNO
Show Them No Mercy! 1935 DVDRip x264
Somebody Killed Her Husband 1978 DVDRip x264-KNT
The Lady and the Monster 1944 DVDRip XViD
Magnolia 1999 1080p BluRay 1080p DTS x264-PRoDJi
Threads 1984 1080p BluRay REMUX AVC FLAC 2 0-EPSiLON
Network 1976 1080p BluRay REMUX AVC DTS-HD MA 1 0-EPSiLON
The Fortune 1975 720p BluRay x264-SPOOKS
Darkest Hour 2017 BluRay 1080p DD5 1 x264-CHD
The Quiet Man 1952 REMASTERED DVDRip x264-REGRET
The Pride of the Yankees 1942 EXTRAS DVDRip x264-REGRET
The Cosmic Man 1959 DVDRip x264-REGRET
Munna Bhai M B B S 2003 iNTERNAL DVDRip x264-REGRET
D O A 1949 iNTERNAL DVDRip x264-REGRET
Live Free or Die Hard (Theatrical and Unrated) - Nakatomi Plaza Collection - Disc 4 - 1080p - Bluray - MKV \ FLAC \ MP3
Die Hard with a Vengeance - Nakatomi Plaza Collection - Disc 3 - 1080p - Bluray - MKV \ FLAC \ MP3
The Adventurers 2017 LIMITED BDRip x264-BiPOLAR
The Last Horror Movie 2003 iNTERNAL DVDRip x264-REGRET
Snow Day 2000 iNTERNAL DVDRip x264-REGRET
Seekers Vol 8-A Haunting On Dice Road 2 Town of the Dead 2017 DVDRip x264-REGRET
Senseless 1998 BluRay 1080p DTS-HD MA 2 0 AVC REMUX-FraMeSToR
Monsters 2010 BluRay 1080p DTS-HD MA 7 1 AVC REMUX-FraMeSToR
The Adventurers 2017 LIMITED 480p x264-mSD
Hangar 18 1980 BluRay 1080p DTS-HD MA 1 0 AVC REMUX-FraMeSToR
Pathfinder 2007 BluRay 1080p DTS-HD MA 5 1 AVC REMUX-FraMeSToR
Assignment Outer Space 1960 iNTERNAL DVDRip x264-REGRET
Three Billboards Outside Ebbing Missouri 2017 DVDRip XviD AC3-iFT
Die Hard 2: Die Harder - Nakatomi Plaza Collection - Disc 2 - 1080p - Bluray - MKV \ FLAC \ MP3
Hellraiser Judgment 2018 BRRip XviD AC3-EVO
Hellraiser Judgment 2018 1080p BluRay X264-PSYCHD
Murder on the Orient Express 2017 1080p BluRay x264 DTS-WiKi
Professor Marston and the Wonder Women 2017 BluRay 1080p DTS x264-PRoDJi
Just Getting Started 2017 720p BRRip X264 AC3 MutzNutz
Drag Me to Hell 2009 UNRATED REMASTERED 720p BluRay X264-AMIABLE
Drag Me to Hell 2009 UNRATED REMASTERED 1080p BluRay X264-AMIABLE
Die Hard - Nakatomi Plaza Collection - Disc 1 - 1080p - Bluray - Die Hard - MKV \ FLAC \ MP3
Three Billboards Outside Ebbing Missouri 2017 1080p BluRay x264-SPARKS
Three Billboards Outside Ebbing Missouri 2017 BRRip XviD AC3-EVO
Three Billboards Outside Ebbing Missouri 2017 720p BRRip X264 AC3-EVO
Three Billboards Outside Ebbing Missouri 2017 BDRip x264-SPARKS
Three Billboards Outside Ebbing Missouri 2017 720p BluRay x264-SPARKS
The Thomas Crown Affair 1968 REMASTERED 1080p BluRay X264-AMIABLE
[REQ] Ghost Shark 2013 1080p BluRay x264-RUSTED
Mozambique 1964 720p BluRay x264 x0r
Darkest Hour 2017 DVDRip XviD AC3-iFT
Dear Brigitte 1965 720p BluRay x264 x0r
The King of Comedy 1982 720p BluRay x264 x0r
[REQ] The Funhouse 1981 1080p BluRay X264-7SinS
Night of the Living Dead 1968 REMASTERED 1080p BluRay X264-AMIABLE
The Florida Project 2017 1080p BluRay REMUX AVC DTS-HD MA 5 1-EPSiLON
The Ballad of Lefty Brown 2017 720p BluRay x264 x0r
Just Getting Started 2017 1080p BluRay x264-DRONES
The Ballad of Lefty Brown 2017 1080p BluRay X264-AMIABLE
Just Getting Started 2017 BRRip XviD AC3-EVO

**Comment by ProfChaos** [comment]
The `parser.GetTitle` doesn't really work without all the other functions :sweat_smile: Since it has to figure out all the other parts and what is left is basically the title.

I changed how the ParseName function works so it directly returns the Torrent struct. It is added to the readme. Hopefully this works for you

**Comment by jasonbronson** [comment]
It looks better but it still struggles with these names

Future of Food Documentary Collection [Nyc]
Silent Night, Deadly Night 1-5 (MBDAPIMP) *THC*
The Philadelphia Story {Cary Grant} 40s
Basic Freestyle Swimming Technique [HuntR][PDU]

If you want the full list of the ones processed you can run it against that sample file I provided.
